"use client";

import React from 'react';
import {
    ArrowRight,
    BookOpen,
    Zap,
    Shield,
    Workflow,
    Cpu,
    Box,
    Terminal,
    Sparkles
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import Link from 'next/link';

export default function DocsIntroduction() {
    return (
        <div className="space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-700">
            {/* Hero Section */}
            <div className="space-y-4">
                <div className="inline-flex items-center gap-2 text-primary bg-primary/10 px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest">
                    <BookOpen size={12} />
                    Documentation
                </div>
                <h1 className="text-4xl md:text-5xl font-black tracking-tight text-foreground leading-tight">Welcome to LogicBricks</h1>
                <p className="text-xl text-muted-foreground font-medium leading-relaxed">
                    Learn how to build, deploy, and scale powerful AI-driven backend logic without writing boilerplate code.
                </p>
            </div>

            <hr className="border-border" />

            {/* Quick Overview */}
            <section className="space-y-6">
                <h2 className="text-2xl font-bold tracking-tight text-foreground">What is LogicBricks?</h2>
                <p className="text-muted-foreground leading-relaxed">
                    LogicBricks is a visual development platform for creating backend logic flows. Unlike traditional no-code tools that limit your flexibility, LogicBricks combines the ease of a visual canvas with the power of AI-generated JavaScript.
                </p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4">
                    <div className="p-6 rounded-2xl border border-border bg-muted/40 space-y-3">
                        <div className="w-10 h-10 rounded-xl bg-blue-500/10 flex items-center justify-center text-blue-600 dark:text-blue-400">
                            <Workflow size={20} />
                        </div>
                        <h4 className="font-bold text-foreground">Visual Canvas</h4>
                        <p className="text-sm text-muted-foreground">Drag and drop nodes to define the execution path of your data.</p>
                    </div>
                    <div className="p-6 rounded-2xl border border-border bg-muted/40 space-y-3">
                        <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center text-emerald-600 dark:text-emerald-400">
                            <Sparkles size={20} />
                        </div>
                        <h4 className="font-bold text-foreground">AI Generation</h4>
                        <p className="text-sm text-muted-foreground">Describe complex logic in English and watch AI write optimized JS for you.</p>
                    </div>
                </div>
            </section>

            {/* Core Concepts */}
            <section className="space-y-6">
                <h2 className="text-2xl font-bold tracking-tight text-foreground">The Three Pillars</h2>
                <p className="text-muted-foreground leading-relaxed">
                    Every logic flow in LogicBricks is built using three primary components, which we call "Bricks".
                </p>

                <div className="space-y-8 pt-4">
                    <div className="flex gap-6 group">
                        <div className="shrink-0 w-12 h-12 rounded-2xl bg-foreground flex items-center justify-center text-background shadow-lg shadow-foreground/10">
                            <Zap size={24} />
                        </div>
                        <div>
                            <h4 className="text-lg font-bold mb-1 text-foreground">1. Start Node (Triggers)</h4>
                            <p className="text-muted-foreground leading-relaxed">The entry point of your flow. This defines how your logic is triggered—whether it's an API call, a scheduled cron job, or a webhook from a third-party service like Stripe or GitHub.</p>
                        </div>
                    </div>

                    <div className="flex gap-6 group">
                        <div className="shrink-0 w-12 h-12 rounded-2xl bg-primary flex items-center justify-center text-primary-foreground shadow-lg shadow-primary/20">
                            <Cpu size={24} />
                        </div>
                        <div>
                            <h4 className="text-lg font-bold mb-1 text-foreground">2. Process Node (Logic)</h4>
                            <p className="text-muted-foreground leading-relaxed">Where the magic happens. You can chains multiple process nodes to filter data, call external APIs, or execute custom JavaScript logic generated by our AI.</p>
                        </div>
                    </div>

                    <div className="flex gap-6 group">
                        <div className="shrink-0 w-12 h-12 rounded-2xl bg-muted flex items-center justify-center text-muted-foreground shadow-lg shadow-muted/20">
                            <Box size={24} />
                        </div>
                        <div>
                            <h4 className="text-lg font-bold mb-1 text-foreground">3. End Node (Response)</h4>
                            <p className="text-muted-foreground leading-relaxed">The final destination. This node determines what data is sent back to the requester or which downstream service is notified once the execution is complete.</p>
                        </div>
                    </div>
                </div>
            </section>

            {/* Next Steps */}
            <section className="p-8 rounded-3xl bg-foreground text-background space-y-6 relative overflow-hidden">
                <div className="absolute top-0 right-0 w-64 h-64 bg-primary/20 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 pointer-events-none" />
                <div className="relative z-10 space-y-4">
                    <h3 className="text-2xl font-bold tracking-tight italic">Ready to build your first flow?</h3>
                    <p className="text-background/60">Jump right in with our Quickstart guide or browse our templates gallery.</p>
                    <div className="flex items-center gap-4 pt-2">
                        <Link href="/docs/quickstart">
                            <Button className="bg-background text-foreground hover:bg-background/90 rounded-xl px-6 font-bold">
                                Quickstart Guide
                            </Button>
                        </Link>
                        <Link href="/dashboard/templates">
                            <Button variant="ghost" className="text-background hover:bg-background/10 rounded-xl font-bold flex items-center gap-2">
                                Browse Templates
                                <ArrowRight size={16} />
                            </Button>
                        </Link>
                    </div>
                </div>
            </section>

            {/* Footer Navigation */}
            <div className="flex items-center justify-between pt-12 border-t border-border">
                <div />
                <Link href="/docs/quickstart">
                    <Button variant="outline" className="rounded-xl font-bold gap-3 group border-border">
                        Quickstart
                        <ArrowRight size={16} className="transition-transform group-hover:translate-x-1" />
                    </Button>
                </Link>
            </div>
        </div>
    );
}
